canCoderID = 22
limitSwitchPort = 8
followerOpposeMaster = true

stowPosition = 0.0
sourceIntakePosition = 3.8
l2ScoringPosition = 27.73
l3ScoringPosition = 27.73
l4ScoringPosition = 20.88
 
 maxExtenstion = 34.762