canCoderID = 22
limitSwitchPort = 8
followerOpposeMaster = true

stowPosition = 0.0
sourceIntakePosition = -31.3
l2ScoringPosition = -6.3
l3ScoringPosition = -6.3
l4ScoringPosition = -14.84
 
 maxExtenstion = -34.762