kHomePosition = 0;
kCruiseVelocity = 0;
kAcceleration = 0;
kMaxUnitsLimit = 0;
kMinUnitsLimit = 0;
kEnableSupplyCurrentLimit = 0;
kSupplyCurrentLimit = 0;
kSupplyCurrentThreshold = 0;
kSupplyCurrentTimeout = 0;
kMaxForwardOutput = 0;
kMaxReverseOutput = 0;