limitSwitch1Port = 1
limitSwitch2Port = 2
followerOpposeMaster = true

maxExtension = -40.69
sourceIntakePosition = -0.3686
l2ScoringPosition = -0.3686
l3ScoringPosition = -18.26
l4ScoringPosition = -40.69