# DO NOT CHANGE these bruh, 
# these are HOly.  If Christian 
# finds a git diff on this he will
# destroy who changes them bruh

# Strafe values
kp_strafe = 3.3
kd_strafe = 3.0

# Forward values
kp_distance = 1.0
kd_distance = 1.0
